package export

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/qiangli/gfy/pkg/graph"
)

var nonAlphaNumRe = regexp.MustCompile(`[^A-Za-z0-9_]`)

func cypherEscape(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "'", "\\'")
	return s
}

func safeNodeLabel(label string) string {
	s := nonAlphaNumRe.ReplaceAllString(label, "")
	if s == "" || (s[0] >= '0' && s[0] <= '9') {
		return "Entity"
	}
	return s
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

func safeRelation(relation string) string {
	s := strings.ReplaceAll(relation, " ", "_")
	s = strings.ReplaceAll(s, "-", "_")
	s = strings.ToUpper(s)
	s = nonAlphaNumRe.ReplaceAllString(s, "_")
	if s == "" {
		return "RELATED_TO"
	}
	return s
}

// ToCypher writes Neo4j Cypher CREATE statements for importing the graph.
func ToCypher(g *graph.Graph, outputPath string) error {
	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return err
	}

	var b strings.Builder
	b.WriteString("// Neo4j Cypher import — generated by gfy\n\n")

	// Nodes
	for _, id := range g.Nodes() {
		attrs := g.NodeAttrs(id)
		fileType := attrStr(attrs, "file_type", "entity")
		label := attrStr(attrs, "label", id)
		nodeLabel := safeNodeLabel(capitalize(fileType))
		fmt.Fprintf(&b, "MERGE (n:%s {id: '%s', label: '%s'});\n",
			nodeLabel, cypherEscape(id), cypherEscape(label))
	}

	b.WriteString("\n")

	// Edges
	for _, e := range g.Edges() {
		relation := safeRelation(attrStr(e.Attrs, "relation", "RELATED_TO"))
		confidence := attrStr(e.Attrs, "confidence", "EXTRACTED")
		fmt.Fprintf(&b, "MATCH (a {id: '%s'}), (b {id: '%s'}) MERGE (a)-[:%s {confidence: '%s'}]->(b);\n",
			cypherEscape(e.Source), cypherEscape(e.Target), relation, cypherEscape(confidence))
	}

	return os.WriteFile(outputPath, []byte(b.String()), 0o644)
}
